### ISSUE TITLE
Nodes in MVC action arguments lead to exception

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#3515]
### Description

Trying to map a `Node` object to a action controller argument fails with Neos 7.2 with an exception

> Too few arguments to function Neos\ContentRepository\Domain\Service\Cache\FirstLevelNodeCache_Original::getChildNodesByPathAndNodeTypeFilter(), 0 passed in /Packages/Libraries/neos/utility-objecthandling/Classes/ObjectAccess.php on line 141 and exactly 2 expected

### Steps to Reproduce

1. Create a (module) controller that expects a node:
```php
    public function showAction(Node $someNode): void
    {
        // ...
    }
```
2. Invoke the action (e.g. via `?moduleArguments[someNode][__contextNodePath]=/some/node-path@live;

#### Expected behavior

The argument is properly converted into an instance of `Node`

#### Actual behavior

The above exception occurs

### Affected Versions

Neos: 7.2

## Background

Apparently this is a regression introduced with #3411 that leads to the `GenericObjectValidator` trying to validate the `Node.context.firstLevelNodeCache` that was previously explicitly excluded from validation.
